### ISSUE TITLE
Migrate HPD violations to import script

### ISSUE THREAD

**Issue by chrishenry** [chrishenry/deltanyc-heatseek#112]
Code for import is currently in https://github.com/chrishenry/deltanyc-heatseek/blob/master/JPF/mysql.skeleton.ipynb.

**Comment by rdlester** [comment]
I'm on it.

**Comment by rdlester** [comment]
I can't get JP's import to work in a script due to pandas errors that don't make any sense, but regardless, the old import was open violations only. We want all violations. We'll need to scrape all the zip files off of http://www1.nyc.gov/site/hpd/about/violation-open-data.page.

zip file format is defined in https://data.cityofnewyork.us/api/views/wvxf-dwi5/files/d1c8828f-bb06-45cf-a70e-01fc815b001d?download=true&filename=HPD%20Violation%20Open%20Data.pdf

**Comment by aepyornis** [comment]
still need this to be done?  i have a working script for postgres (https://github.com/aepyornis/hpd-violations), probably not to hard to convert to mysql, which i could help with.

**Comment by rdlester** [comment]
I've got some work in progress, I'm pretty much most of the way there, just need some time to finish, probably next week.

The extra feature I've added to the import is running the entire thing through Luigi, with individual tasks for the raw zip download / unzip and the imports. In theory, this should also provide incremental import for free.

**Comment by rdlester** [comment]
But, if it's relatively straightforward to plug in your version, go ahead, then take a look at building the Rails db_connector for the violations. I'll likely swap my import script in, b/c of incremental, but the db_connector should be the same (until we switch that to run incrementally as well).

**Comment by aepyornis** [comment]
@rdlester sounds good

**Comment by rdlester** [comment]
See #175 for work in progress.
