### ISSUE TITLE
Many rails tables have empty columns

### ISSUE THREAD

**Issue by LKWLaLa** [chrishenry/deltanyc-heatseek#131]
If you navigate to a property show page in the web app and QA the user interface by clicking to view the tables, you will notice there are many blank columns.  When PR #130 is merged, you will have access to the table endpoints to look at this, but for now the quickest way to see this is to run the app at `localhost:3000` and view a property.  You could try 1749 Grand Concourse, Bronx for starters.

Many tables have blank columns, but for example, here is DOB Permits:
![image](https://cloud.githubusercontent.com/assets/15372198/25063974/67ae6e76-21be-11e7-8375-eb1813897073.png)

**Comment by rdlester** [comment]
We definitely want to leave dates in timestamp format inside the database, as I don't think you can accurately do things like order by date without storing dates as such. Instead, you'll need to process the date either on the front end or in the rails controller to human readable format. Both JS and Ruby should have utils to take care of this in the standard library.

Looking into the missing columns now.

If I have to dive too deep into the Rake task code, I might ditch them and skip straight to running the connectors as Luigi tasks.

**Comment by rdlester** [comment]
@LKWLaLa - it would be very helpful if you could post a list of every column that is missing; it would save me a lot of time in double checking every single column.

I already fixed the two important columns - they were broken due to typos (filling v filing). The others are probably the same.

**Comment by LKWLaLa** [comment]
@rdlester  You can see pretty quickly what is missing if you glance at the front end.  Apologies, but I won't have a lot of time to work this week (and am writing on the go now), so I wouldn't be able to write out a comprehensive list for a while.  Thanks for looking at this though!  And yes, you are right, the human readable format is a front end thing.  I will fix that part myself.

**Comment by rdlester** [comment]
Okay, that's fine, I'll keep plugging through the connector tasks.

So far:
- dob_permits: filing misspelled as filling. Need to fix column name in database schema as well.
- dob_violations: should probably include violation_type_code in the database?
- hpd_complaints: using borough numerical ID instead of two-letter borough code for looking up properties, resulting in no complaints being imported. (still needs work to merge with hpd_complaints_problems, but that's a separate issue)
- hpd_litigations: also using borough numerical ID instead of two-letter code.
- three11: fine, but doing a bunch of junk to convert the numerical code from the geocoder result to the two-letter code when the two-letter code already exists in the original table.

**Comment by rdlester** [comment]
- owners: r_owners has a column named hpd_type, but that column is never set in the rake task. I don't know what "hpd_type" refers to, so I can't really fix it - it's either something someone forgot to add, or added when we were starting out but is no longer needed.
- properties: total_units is only set for buildings in PLUTO but not HPD, as the HPD data does not contain that info. Instead of "INSERT IGNORE"-ing data from each table in sequence, we should join the two tables directly. bin and rent_stabilized are never set. bin can probably be removed; rent_stabilized will need to be populated with a join against the rent_stabilization table (which should go in a separate issue).

**Comment by LKWLaLa** [comment]
@rdlester Thanks so much!  I will have more time this weekend, so I will send you over a complete list of what is blank (at least on my end, pre - any changes you made above) on saturday.  Are you somehow not able to run the app in your browser and quickly view the tables that way?

**Comment by rdlester** [comment]
Figured out hpd_type in owners.

**Comment by rdlester** [comment]
This is fixed. Will try to link in related PRs.
